Project: NEW6

InputData:
  # First step, the user have to define the type of data to be processed, OnServer or OnDisk.
  Datatype: 'OnServer'
#  Datatype: 'OnDisk'
  start_time: '2013-04-09 00:00:00.00'
  end_time: '2013-04-10 00:00:00.00'
  sta_json_name: 'station_list.json'
  data_save_name: 'ori_data'
  DataDownload:
    channel_list: [ "HH[ZNE]", "HH[Z21]", "BH[ZNE]","BH[Z21]","EH[ZNE]","EH[Z21]","SH[Z21]","SH[ZNE]","HN[ZNE]", "HN[Z23]" ]
    exclude_network: [ 'SY','AF' ]
    minlat: 5.0
    maxlat: 8.0
    minlon: -2.0
    maxlon: 1.0
    client_list: [ "IRIS" ]

  DataFormat:
    #  channel_list: ["HH[ZNE]", "HH[Z21]", "BH[ZNE]","BH[Z21]","EH[ZNE]","EH[Z21]","SH[Z21]","SH[ZNE]","HN[ZNE]", "HN[Z23]"]
#    include_network: [ 'SY','AF' ]
    seisdatastru_input: 'SDS'
    station_inv: './OnDiskData/station_inventory_Ghana.csv'
    station_inv_input: './OnDiskData/Inputdata_xml'
    station_inv_output: 'ori_dataxml'
    instrument_code: ["HHZ","HHN","HHE"]
    dir_seismic_input: './OnDiskData/GhanaOnDiskSeiscomp'
    dir_seismic_output: 'ori_data'
#    sta_json_name: 'station_list.json'
    freqband: [1, 100]
    split: False

EqT:
  mseed_dir: 'ori_data'
  sta_json_path: 'station_list.json'
  overlap: 0.9
  n_processor: 8
  det_res: detection_results
  model_path: '../models/EqT/EqT_model.h5'
  gpuid: '3'
  number_of_sampling: 5
  EQ_threshold: 0.2
  P_threshold: 0.05
  S_threshold: 0.05
  txt_folder: ./EqTPicks/
  STAXML: 'ori_dataxml'

S_EqT:
  txt_folder: ./SEqTPicks/
  P_branch_config: '../src/S_EqT_codes/configs/P_branch.yaml'
  P_branch_model: '../models/S_EqT/S_EqT_P_branch.hdf5'
  P_threshold: 0.1
  P_skip_threshold: 0.8
  keep_time_range_P: 8.0
  S_branch_config: '../src/S_EqT_codes/configs/S_branch.yaml'
  S_branch_model: '../models/S_EqT/S_EqT_S_branch.hdf5'
  S_threshold: 0.1
  S_skip_threshold: 0.8
  keep_time_range_S: 16.0
  max_search_distance: 110
  exist_range: 20.0

REAL:
  ref_time: '2013-04-09'
  save_sta: 'sta_info_real_format.dat'
  year: ["\"2013\""]
  mon: ["\"04\""]
  day: ["\"09\""]
  R: "\"0.2/100/0.03/5/0.01\""
  G: "\"0.5/100/0.01/5\""
  V: "\"6.3/3.4/2.0/1.5/0\""
  S: "\"3/1/4/1/2.0/0/5.0/5.0\""
  station: "\"./sta_info_real_format.dat\""
  ttime: "\"../REAL_scripts/tt_db/ttdb.txt\""
  seqt_dir: "./SEqTPicks/"
  seqt_catalog_dir: "./SEqTCatalogs/"
  primary_event_dir: "primary_events"

MIL:
  seismic:
    dir: "../OnDiskData/GH_events/2012-10-08-12-28-57"
    instrument_code: ["HH"]
    stainvf: "./OnDiskData/station_inventory_Ghana.csv"
    freqband: [1, 50]
    datastru: "EVS"
  control:
    dir_output: "MIL_OUTPUTS"
    n_processor: 6
  tt:
    vmodel: './OnDiskData/velocity_ghana.txt'
    dir: 'traveltime/tt_1km'
    build: True
  # %% ML detection parameters======================================================
  detect:
    twind_srch: 180  # time window length in second where events will be searched in this range
    twlex: 1.0  # time in second for extend the time window, roughly equal to the width of P- or S-probability envelope
    P_thrd: 0.001  # probability threshold for detecting P-phases/events from the ML-predicted phase probabilities
    S_thrd: 0.001  # probability threshold for detecting S-phases/events from the ML-predicted phase probabilities
    nsta_thrd: 1  # minimal number of stations triggered during the specified event time period
    npha_thrd: 1  # minimal number of phases triggered during the specified event time period
   # %% migration location, grid search parameters======================================================
  grid :
    LatOrig: 4.7  # latitude in decimal degrees of the origin point of the rectangular migration region (float, min:-90.0, max:90.0)
    LongOrig: -2.5  # longitude in decimal degrees of the origin point of the rectangular migration region (float, min:-180.0, max:180.0)
    zOrig: -0.4  # Z location of the grid origin in km relative to the sea-level. Nagative value means above the sea-level; Positive values for below the sea-level;
    xNum: 426  # number of grid nodes in the X direction (East)
    yNum: 310  # number of grid nodes in the Y direction (North)
    zNum: 51  # number of grid nodes in the Z direction (Vertical-down)
    dgrid: 1  # grid spacing in kilometers

  # %% migration parameters======================================================
  MIG :
    ppower: None
    output_migv: False
  CAT :
    dir_output: 'catalog'
    fname: 'Ghana'
    fformat: 'csv'
  ML :
    engine: 'seisbench'
    model: 'EQTransformer.original'
    overlap: 0.9